/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvsRouteImport } from './routes/tvs'
import { Route as TabletsRouteImport } from './routes/tablets'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as PhonesRouteImport } from './routes/phones'
import { Route as PcsRouteImport } from './routes/pcs'
import { Route as MonitorsRouteImport } from './routes/monitors'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaptopsRouteImport } from './routes/laptops'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GamingRouteImport } from './routes/gaming'
import { Route as DronesRouteImport } from './routes/drones'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'

const TvsRoute = TvsRouteImport.update({
  id: '/tvs',
  path: '/tvs',
  getParentRoute: () => rootRouteImport,
} as any)
const TabletsRoute = TabletsRouteImport.update({
  id: '/tablets',
  path: '/tablets',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const PhonesRoute = PhonesRouteImport.update({
  id: '/phones',
  path: '/phones',
  getParentRoute: () => rootRouteImport,
} as any)
const PcsRoute = PcsRouteImport.update({
  id: '/pcs',
  path: '/pcs',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorsRoute = MonitorsRouteImport.update({
  id: '/monitors',
  path: '/monitors',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaptopsRoute = LaptopsRouteImport.update({
  id: '/laptops',
  path: '/laptops',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GamingRoute = GamingRouteImport.update({
  id: '/gaming',
  path: '/gaming',
  getParentRoute: () => rootRouteImport,
} as any)
const DronesRoute = DronesRouteImport.update({
  id: '/drones',
  path: '/drones',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/cart': typeof CartRoute
  '/components': typeof ComponentsRoute
  '/deals': typeof DealsRoute
  '/drones': typeof DronesRoute
  '/gaming': typeof GamingRoute
  '/help': typeof HelpRoute
  '/laptops': typeof LaptopsRoute
  '/login': typeof LoginRoute
  '/monitors': typeof MonitorsRoute
  '/pcs': typeof PcsRoute
  '/phones': typeof PhonesRoute
  '/servers': typeof ServersRoute
  '/tablets': typeof TabletsRoute
  '/tvs': typeof TvsRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/cart': typeof CartRoute
  '/components': typeof ComponentsRoute
  '/deals': typeof DealsRoute
  '/drones': typeof DronesRoute
  '/gaming': typeof GamingRoute
  '/help': typeof HelpRoute
  '/laptops': typeof LaptopsRoute
  '/login': typeof LoginRoute
  '/monitors': typeof MonitorsRoute
  '/pcs': typeof PcsRoute
  '/phones': typeof PhonesRoute
  '/servers': typeof ServersRoute
  '/tablets': typeof TabletsRoute
  '/tvs': typeof TvsRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/cart': typeof CartRoute
  '/components': typeof ComponentsRoute
  '/deals': typeof DealsRoute
  '/drones': typeof DronesRoute
  '/gaming': typeof GamingRoute
  '/help': typeof HelpRoute
  '/laptops': typeof LaptopsRoute
  '/login': typeof LoginRoute
  '/monitors': typeof MonitorsRoute
  '/pcs': typeof PcsRoute
  '/phones': typeof PhonesRoute
  '/servers': typeof ServersRoute
  '/tablets': typeof TabletsRoute
  '/tvs': typeof TvsRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessories'
    | '/cart'
    | '/components'
    | '/deals'
    | '/drones'
    | '/gaming'
    | '/help'
    | '/laptops'
    | '/login'
    | '/monitors'
    | '/pcs'
    | '/phones'
    | '/servers'
    | '/tablets'
    | '/tvs'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessories'
    | '/cart'
    | '/components'
    | '/deals'
    | '/drones'
    | '/gaming'
    | '/help'
    | '/laptops'
    | '/login'
    | '/monitors'
    | '/pcs'
    | '/phones'
    | '/servers'
    | '/tablets'
    | '/tvs'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/accessories'
    | '/cart'
    | '/components'
    | '/deals'
    | '/drones'
    | '/gaming'
    | '/help'
    | '/laptops'
    | '/login'
    | '/monitors'
    | '/pcs'
    | '/phones'
    | '/servers'
    | '/tablets'
    | '/tvs'
    | '/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoriesRoute: typeof AccessoriesRoute
  CartRoute: typeof CartRoute
  ComponentsRoute: typeof ComponentsRoute
  DealsRoute: typeof DealsRoute
  DronesRoute: typeof DronesRoute
  GamingRoute: typeof GamingRoute
  HelpRoute: typeof HelpRoute
  LaptopsRoute: typeof LaptopsRoute
  LoginRoute: typeof LoginRoute
  MonitorsRoute: typeof MonitorsRoute
  PcsRoute: typeof PcsRoute
  PhonesRoute: typeof PhonesRoute
  ServersRoute: typeof ServersRoute
  TabletsRoute: typeof TabletsRoute
  TvsRoute: typeof TvsRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tvs': {
      id: '/tvs'
      path: '/tvs'
      fullPath: '/tvs'
      preLoaderRoute: typeof TvsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tablets': {
      id: '/tablets'
      path: '/tablets'
      fullPath: '/tablets'
      preLoaderRoute: typeof TabletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phones': {
      id: '/phones'
      path: '/phones'
      fullPath: '/phones'
      preLoaderRoute: typeof PhonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pcs': {
      id: '/pcs'
      path: '/pcs'
      fullPath: '/pcs'
      preLoaderRoute: typeof PcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitors': {
      id: '/monitors'
      path: '/monitors'
      fullPath: '/monitors'
      preLoaderRoute: typeof MonitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laptops': {
      id: '/laptops'
      path: '/laptops'
      fullPath: '/laptops'
      preLoaderRoute: typeof LaptopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaming': {
      id: '/gaming'
      path: '/gaming'
      fullPath: '/gaming'
      preLoaderRoute: typeof GamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drones': {
      id: '/drones'
      path: '/drones'
      fullPath: '/drones'
      preLoaderRoute: typeof DronesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoriesRoute: AccessoriesRoute,
  CartRoute: CartRoute,
  ComponentsRoute: ComponentsRoute,
  DealsRoute: DealsRoute,
  DronesRoute: DronesRoute,
  GamingRoute: GamingRoute,
  HelpRoute: HelpRoute,
  LaptopsRoute: LaptopsRoute,
  LoginRoute: LoginRoute,
  MonitorsRoute: MonitorsRoute,
  PcsRoute: PcsRoute,
  PhonesRoute: PhonesRoute,
  ServersRoute: ServersRoute,
  TabletsRoute: TabletsRoute,
  TvsRoute: TvsRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
